// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIUBlhEcHHGOR07NP3OAXdaCZOj1KwSAg',
    appId: '1:576402726315:web:42a25e12db3797d57f86ee',
    messagingSenderId: '576402726315',
    projectId: 'c300-project-e38e7',
    authDomain: 'c300-project-e38e7.firebaseapp.com',
    databaseURL: 'https://c300-project-e38e7-default-rtdb.firebaseio.com',
    storageBucket: 'c300-project-e38e7.appspot.com',
    measurementId: 'G-17DYNWVYGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWgoiIxEo_hc2A5h-g1W9eYy9HEe_-Fus',
    appId: '1:576402726315:android:663658c0a23cd0447f86ee',
    messagingSenderId: '576402726315',
    projectId: 'c300-project-e38e7',
    databaseURL: 'https://c300-project-e38e7-default-rtdb.firebaseio.com',
    storageBucket: 'c300-project-e38e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo8G2WHnokkfLAsO-Lm8IeyOVj54g6Pk0',
    appId: '1:576402726315:ios:184710febe9ce8eb7f86ee',
    messagingSenderId: '576402726315',
    projectId: 'c300-project-e38e7',
    databaseURL: 'https://c300-project-e38e7-default-rtdb.firebaseio.com',
    storageBucket: 'c300-project-e38e7.appspot.com',
    iosClientId: '576402726315-4kdp0rv81pk1q4mbmgj915q6rpefvava.apps.googleusercontent.com',
    iosBundleId: 'com.example.c300drowningdetection',
  );
}
