// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi2Rn2gVP78GL6SpCMYuSsmLNamHh9wKE',
    appId: '1:609484616252:web:08efa9d1e050dc9b0cc939',
    messagingSenderId: '609484616252',
    projectId: 'c300-drowning-detection-system',
    authDomain: 'c300-drowning-detection-system.firebaseapp.com',
    databaseURL: 'https://c300-drowning-detection-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'c300-drowning-detection-system.appspot.com',
    measurementId: 'G-P1853BVYB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzTGLgQH8CHAECOSZU8hB0hOtXYfHde8',
    appId: '1:609484616252:android:6fa1c2b37f31f38c0cc939',
    messagingSenderId: '609484616252',
    projectId: 'c300-drowning-detection-system',
    databaseURL: 'https://c300-drowning-detection-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'c300-drowning-detection-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDohMk8dvd8zgoqwmr4X5c-SGBy8eGuL7c',
    appId: '1:609484616252:ios:cf021480290a9caf0cc939',
    messagingSenderId: '609484616252',
    projectId: 'c300-drowning-detection-system',
    databaseURL: 'https://c300-drowning-detection-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'c300-drowning-detection-system.appspot.com',
    iosClientId: '609484616252-cfqdbnnjoe5pm4hassvvhku4bc28fesp.apps.googleusercontent.com',
    iosBundleId: 'com.example.c300drowningdetection',
  );
}
